#!/usr/bin/env php
<?php
// by @leaskh

require_once dirname(__FILE__) . '/common.php';
require_once dirname(__FILE__) . '/DataModel.php';

class UpdateAutoCompleteIndex extends DataModel {

    public function run() {
        $redis = new Redis();
        $redis->connect(REDIS_SERVER_ADDRESS, REDIS_SERVER_PORT);
        $keys = $redis->keys('u:*');
        // loop
        foreach ($keys ?: [] as $key) {
            echo "Delete Auto Complete Index for id {$key} .\r\n";
            $redis->del($key);
        }
        //
        echo "\r\nDone.\r\n";
    }

}

$upgradeObj = new UpdateAutoCompleteIndex();
$upgradeObj->run();
