#!/usr/bin/env php
<?php
// by @leaskh

error_reporting(E_ALL ^ E_NOTICE);

define('HELPER_DIR', dirname(__FILE__) . '/helpers');
define('MODEL_DIR',  dirname(__FILE__) . '/models');

require_once dirname(__FILE__) . '/common.php';
require_once dirname(__FILE__) . '/DataModel.php';
require_once 'FrontController.php';


class wechatcli extends DataModel {

    public $hlpWechat = null;


    public function __construct() {
        $this->hlpWechat = $this->getHelperByName('Wechat');
    }


    public function getMenu() {
        $rawMenu = $this->hlpWechat->getMenu();
        if ($rawMenu) {
            print_r($rawMenu);
        } else {
            echo "menu no exist!\r\n";
        }
    }


    public function createMenu() {
        $menu = [
            "button" => [
                [
                    "type" => "click",
                    "name" => "活点地图",
                    "key"  => "V1001_TODAY_MUSIC"
                ],
                [
                    "type" => "click",
                    "name" => "创建地图",
                    "key"  => "V1001_TODAY_SINGER"
                ],
                [
                    "name" => "帮助",
                    "sub_button" => [
                        [
                            "type" => "click",
                            "name" => "菜单一",
                            "key"  => "V1001_HELLO_WORLD"
                        ],
                        [
                            "type" => "click",
                            "name" => "菜单二",
                            "key"  => "V1001_GOOD"
                        ]
                    ]
                ]
            ]
        ];
        $rawMenu = $this->hlpWechat->createMenu($menu);
        if ($rawMenu) {
            print_r($rawMenu);
        } else {
            echo "Failed!\r\n";
        }
    }


    public function deleteMenu() {
        $rawResult = $this->hlpWechat->deleteMenu();
        if ($rawResult) {
            echo "Done!\r\n";
        } else {
            echo "Failed!\r\n";
        }
    }


    public function run() {
        // $redis = new Redis();
        // $redis->connect(REDIS_SERVER_ADDRESS, REDIS_SERVER_PORT);
        // $keys = $redis->keys('u:*');
        // // loop
        // foreach ($keys ?: [] as $key) {
        //     echo "Delete Auto Complete Index for id {$key} .\r\n";
        //     $redis->del($key);
        // }
        // //
        // echo "\r\nDone.\r\n";
    }

}

$objWechatcli = new wechatcli();
array_shift($argv);

switch (strtolower($argv[0])) {
    case 'getmenu':
        $objWechatcli->getMenu();
        break;
    case 'createmenu':
        $objWechatcli->createMenu();
        break;
    case 'deletemenu':
        $objWechatcli->deleteMenu();
        break;
    default:
        echo "WeChatCli: invalid option -- '{$argv[0]}'\r\n";
        echo "try: getmenu, createmenu, deletemenu.\r\n";
        exit(1);
}
