<?php
return array(
    'js_libs'=>array(
        'js/libs/jquery.js',
        'js/libs/activity-indicator.js',
        'js/libs/jquery.ba-outside-events.js',
        'js/libs/jquery.ba-dotimeout.js',
        'js/libs/detect_timezone.js',
        'js/libs/jquery.imgareaselect.js',
    ),
    'js_util'=>array(
        'js/comm/ExfeUtil.js',
        'js/exlibs/ExDialog.js',
    ),
    'js_user'=>array(
        'js/user/UserStatus.js',
        'js/user/UserIdentification.js',
        'js/user/UserProfile.js',
    ),
    'js_uploader'=>array(
        'js/user/UploadAvatar.js',
        'js/user/FileUploader.js',
    ),
    'css_global'=>array(
        'css/global.css',
        'css/style.css'
    )
);
