#!/bin/sh
function_start_jobs(){
printf "Starting queue...\n"
/usr/local/etc/rc.d/phpresqueapn
/usr/local/etc/rc.d/phpresqueemail
/usr/local/etc/rc.d/phpconversationemail
/usr/local/etc/rc.d/phpresquewaiting
}

function_stop_jobs(){
    printf "Stoping queue...\n"
    tokill=`ps aux |grep resque | grep 'www'|awk '{printf $2" "}'`;
    echo $tokill
    kill $tokill
}
if [ "$1" = "start" ]; then
    function_start_jobs
elif [ "$1" = "restart" ]; then
    function_stop_jobs
    function_start_jobs
elif [ "$1" = "stop" ]; then
    function_stop_jobs
else
    printf "Usage:/usr/local/etc/rc.d/phpresque {start|stop|restart}\n"
fi
